name = "neko"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "tutturuu.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.tutturuu.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.tutturuu.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.tutturuu.web.id", custom_domain = true },
  { pattern = "help.viu.com.tutturuu.web.id", custom_domain = true },
  { pattern = "support.zoom.us.tutturuu.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.tutturuu.web.id", custom_domain = true },
  { pattern = "graph.facebook.com.tutturuu.web.id", custom_domain = true },
  { pattern = "dogseechew.com.tutturuu.web.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "fa7aef2afe4643168dae8bc527a914c5"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/Abyy32/WEB/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/Abyy32/WEB/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/Abyy32/WEB/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/Abyy32/WEB/refs/heads/master/web/converter.html"
